language: python

python:
  - "3.5"

sudo: false

install:
  - pip install pylint==2.2.2
  - pip install pycodestyle==2.5.0

script:
  - python3 linters_test.py
  - python3 git_tools_test.py
  - python3 lint.py validate --all
